### PR TITLE
Thread fixes, sharding support, statistics, Redis transactions

### PR DESCRIPTION
**Pull request by jkdufair**
This PR offers the following features/fixes:

- Instantiates a Redis database instance per method, as suggested by the StackOverflow docs
- Lazy initializes the `ConnectionMultiplier` also per recommendations
- Optionally collects and stores cache stats in Redis
- Uses Redis transactions to handle concurrency errors that arise under heavy load

Thanks for taking a look!

### CODE REVIEW

**Comment by silentbobbert** [comment]
Thanks for the PR. Looks like some great improvements here. I haven't forgotten about it, but quite busy at the moment. Cheers!

**Comment by silentbobbert** [comment]
Hi @jkdufair - I have been looking to complete your PR today, however I found your version did not compile. There appears to be missing files? ILockedEntitySet, ILockableCache ??? Can you review your local copy and push the missing files, so that if I do a clean checkout, it will compile?

**Comment by jkdufair** [comment]
Hey sorry for the delay! Thanks for merging this. I presume you found what you needed in the branch we've been working on? Also we have had some issues under heavy load that we are investigating. I'll keep you updated.

**Comment by jkdufair** [comment]
Ok I see it went into a feature branch. Great. We've done some decent amount of revision since the PR. Sorry we didn't keep you updated. Once we sort out the heavy load stuff, I'll open a new PR on to your feature branch?

**Comment by silentbobbert** [comment]
Hi @jkdufair - I looked over your fork, and I cant find the missing files. I hardly ever accept PRs directly to master, so I will ask contributors to retarget to develop or a feature. Your changes were quite large so I wanted to thoroughly review them, build them, and test them before putting in my main branch. I will create a new feature for you called purdue that you can target when you are ready to send in your new PR.

**Pull request merged**
