### PR TITLE
Optimization

### PR DESCRIPTION
**Pull request by tiwariarvin**
- To utilize CommandFlags.FireAndForget where ever possible. Get calls can't take benefit of it because notification from it drives the cache mechanism.
- Removed sync locks from Get calls, realized that it don't need to be atomic.

### CODE REVIEW

**Comment by tiwariarvin** [comment]
Hi Ian - Did you had a chance to look at it? These are some cool changes we came up with, let me know your feedback.

Regards

**Comment by silentbobbert** [comment]
Hi Arvin



Sorry, I have been out of the country for a couple of weeks, so have not
been able to review the changes yet.



I will take a look, probably this weekend – got a lot to catch up on at
work.



Cheers



Ian



*From:* tiwariarvin [mailto:notifications@github.com]
*Sent:* 07 October 2015 15:17
*To:* silentbobbert/EFCache.Redis <EFCache.Redis@noreply.github.com>
*Subject:* Re: [EFCache.Redis] Optimization (#12)



Hi Ian - Did you had a chance to look at it? These are some cool changes we
came up with, let me know your feedback.

Regards

—
Reply to this email directly or view it on GitHub
<https://github.com/silentbobbert/EFCache.Redis/pull/12#issuecomment-146208035>
.

**Comment by tiwariarvin** [comment]
No problem Ian, please take your time.

Cheers

**Comment by silentbobbert** [comment]
Thanks. This pull request has been integrated manually.

**Pull request merged**
